{'name': 'root', 'msg': 'Hermless debig Message', 'args': (), 'levelname': 'DEBUG', 'levelno': 10, 'pathname': 'c:\\Users\\Asus\\Desktop\\OOP & M.py\\loging', 'filename': 'loging', 'module': 'loging', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 11, 'funcName': '<module>', 'created': 1740397402.2787216, 'msecs': 278.0, 'relativeCreated': 2.6043, 'thread': 3908, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 12480, 'taskName': None, 'message': 'Hermless debig Message'}stime)s Hermless debig Message
{'name': 'root', 'msg': 'Informational message', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': 'c:\\Users\\Asus\\Desktop\\OOP & M.py\\loging', 'filename': 'loging', 'module': 'loging', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 13, 'funcName': '<module>', 'created': 1740397402.2789397, 'msecs': 278.0, 'relativeCreated': 2.8223, 'thread': 3908, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 12480, 'taskName': None, 'message': 'Informational message'}stime)s Informational message
{'name': 'root', 'msg': "It's Warning", 'args': (), 'levelname': 'WARNING', 'levelno': 30, 'pathname': 'c:\\Users\\Asus\\Desktop\\OOP & M.py\\loging', 'filename': 'loging', 'module': 'loging', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 15, 'funcName': '<module>', 'created': 1740397402.2790835, 'msecs': 279.0, 'relativeCreated': 2.9662, 'thread': 3908, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 12480, 'taskName': None, 'message': "It's Warning"}stime)s It's Warning
{'name': 'root', 'msg': 'An error occurred', 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': 'c:\\Users\\Asus\\Desktop\\OOP & M.py\\loging', 'filename': 'loging', 'module': 'loging', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 17, 'funcName': '<module>', 'created': 1740397402.2791703, 'msecs': 279.0, 'relativeCreated': 3.0529, 'thread': 3908, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 12480, 'taskName': None, 'message': 'An error occurred'}stime)s An error occurred
{'name': 'root', 'msg': 'Critical error occurred', 'args': (), 'levelname': 'CRITICAL', 'levelno': 50, 'pathname': 'c:\\Users\\Asus\\Desktop\\OOP & M.py\\loging', 'filename': 'loging', 'module': 'loging', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 19, 'funcName': '<module>', 'created': 1740397402.279281, 'msecs': 279.0, 'relativeCreated': 3.1635, 'thread': 3908, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 12480, 'taskName': None, 'message': 'Critical error occurred'}stime)s Critical error occurred
